# Generated by Django 4.2.7 on 2023-11-22 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GAMING', 'GAMING'), ('CAREER', 'CAREER'), ('SCHOOL', 'SCHOOL'), ('STUDENT ORGANIZATIONS', 'STUDENT ORGANIZATIONS'), ('OTHER', 'OTHER')], max_length=25)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='api.post')),
            ],
        ),
    ]
