# Generated by Django 4.2.7 on 2023-11-22 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
