# Generated by Django 4.2.7 on 2023-11-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_categories_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('GAMING', 'GAMING'), ('CAREER', 'CAREER'), ('SCHOOL', 'SCHOOL'), ('STUDENT ORGANIZATIONS', 'STUDENT ORGANIZATIONS')], default='OTHER', max_length=25),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
